api:
  key: 064C44F2A5AF42D3A17BD90431941F6B
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1691060700
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1684929600
      _plugins:
        read_until: 1689552000
      _releases:
        read_until: 1689678900
  bedlevelvisualizer:
    _config_version: 1
    command: |-
      M155 S30  ; set temperature reporting delay, use a value longer than the time it takes for your leveling command to complete.
      G29 P1    ; Take a bed leveling mesh.
      @BEDLEVELVISUALIZER  ; instruct plugin to start recording responses from printer.
      M420 V    ; Get bed leveling mesh data.
      M155 S3   ; set the temperature reporting delay back to a shorter time span.
    descending_y: true
    graph_z_limits: -1,1
    mesh_timestamp: 04/08/2023, 16:23:43
    screw_hub: 0.7
    show_stored_mesh_on_tab: true
    showdegree: true
    stored_mesh:
    - - '+0.03'
      - '+0.05'
      - '+0.06'
      - '+0.04'
      - '+0.03'
    - - '+0.00'
      - '+0.02'
      - '+0.02'
      - '+0.02'
      - '+0.03'
    - - '+0.01'
      - '+0.02'
      - '+0.03'
      - '+0.02'
      - '+0.03'
    - - '-0.02'
      - '+0.01'
      - '+0.02'
      - '+0.03'
      - '+0.06'
    - - '+0.04'
      - '+0.03'
      - '+0.05'
      - '+0.05'
      - '+0.05'
    stored_mesh_x:
    - 30
    - 70
    - 110
    - 149
    - 189
    stored_mesh_y:
    - 30
    - 70
    - 110
    - 149
    - 189
    stored_mesh_z_height: 259
  classicwebcam:
    _config_version: 1
    snapshot: http://127.0.0.1:8080/?action=snapshot
    stream: /webcam/?action=stream
  cura:
    cura_engine: null
  discovery:
    publicPort: 80
    upnpUuid: 2d1e6325-9111-4f05-91a1-23c5150a5167
  errortracking:
    unique_id: 7f594aee-702d-40de-ac34-65eeb8f7e414
  firmwareupdater:
    _config_version: 3
    _selected_profile: 0
    has_bftcapability: true
    profiles:
    - _id: 0
      _name: Default
  gcodeviewer:
    _config_version: 1
  softwareupdate:
    _config_version: 9
  tracking:
    enabled: true
    unique_id: f0395568-4efc-4e0c-b571-83b955aa5677
  uicustomizer:
    mainTabs:
    - - control_link
      - true
      - false
      - fas fa-expand-arrows-alt
      - true
      - false
    - - temp_link
      - true
      - false
      - fas fa-thermometer-half
      - true
      - false
    - - term_link
      - true
      - false
      - fas fa-terminal
      - true
      - false
    - - gcode_link
      - true
      - false
      - fab fa-codepen
      - true
      - false
    - - tab_plugin_bedlevelvisualizer_link
      - true
      - false
      - false
      - textOnly
      - '#000000'
    - - tab_plugin_eeprom_marlin_link
      - true
      - false
      - false
      - textOnly
      - '#000000'
    rows:
    - _00#state_wrapper: true
      _01#files_wrapper: true
      _02#sidebar_plugin_firmware_check_warning_wrapper: false
      _03#sidebar_plugin_firmware_check_info_wrapper: false
      _04#connection_wrapper: true
    - _00div.UICmainTabs: true
    - _00#UICGcodeVWidget: true
      _01#UICTempWidget: true
      _02#UICWebCamWidget: true
      _03#sidebar_plugin_action_command_notification_wrapper: true
    theme: discorded
    themeLocal: false
    themeVersion: 0.2.9.8
    topIconSort:
    - navbar_plugin_firmwareupdater
    - navbar_plugin_action_command_prompt
    - navbar_plugin_logging_seriallog
    - navbar_plugin_logging_plugintimingslog
    - navbar_plugin_pi_support
    widths:
    - '3'
    - '6'
    - '3'
  virtual_printer:
    _config_version: 1
printerProfiles:
  default: _default
serial:
  autoconnect: true
  baudrate: 250000
  port: /dev/ttyUSB0
  sdCancelCommand: M524
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
  firstRun: false
  onlineCheck:
    enabled: true
    host: 8.8.8.8
  pluginBlacklist:
    enabled: true
  secretKey: C8IV33fA2fqF1xS0AyqamrDUSrgbP3Yz
  seenWizards:
    backup: null
    classicwebcam: 1
    corewizard: 4
    tracking: null
temperature:
  profiles:
  - bed: 100
    chamber: null
    extruder: 210
    name: ABS
  - bed: 60
    chamber: null
    extruder: 210
    name: PLA
webcam:
  ffmpeg: /usr/bin/ffmpeg
  timelapseEnabled: false
  watermark: false
  webcamEnabled: false
